export const userConstants = {
  SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
  SET_CURRENT_USER_LOADING: 'SET_CURRENT_USER_LOADING',
  SET_CURRENT_GET_ERRORS: 'SET_CURRENT_GET_ERRORS',
  UPDATE_USER: 'UPDATE_USER',
};
