export const dayNewsConstants = {
  FETCH_NEWS_DAY_DATA_PENDING: 'FETCH_NEWS_DAY_DATA_PENDING',
  FETCH_NEWS_DAY_DATA_SUCCESS: 'FETCH_NEWS_DAY_DATA_SUCCESS',
  FETCH_NEWS_DAY_DATA_FAILURE: 'FETCH_NEWS_DAY_DATA_FAILURE',
};
